INSERT INTO SPACECRAFT (SPACECRAFT_ID, SPACECRAFT_NAME) VALUES (NEXT VALUE FOR SPACECRAFT_SEQ, 'wing-I');
INSERT INTO SPACECRAFT (SPACECRAFT_ID, SPACECRAFT_NAME) VALUES (NEXT VALUE FOR SPACECRAFT_SEQ, 'wing-II');
INSERT INTO SPACECRAFT (SPACECRAFT_ID, SPACECRAFT_NAME) VALUES (NEXT VALUE FOR SPACECRAFT_SEQ, 'wing-III');
INSERT INTO SPACECRAFT (SPACECRAFT_ID, SPACECRAFT_NAME) VALUES (NEXT VALUE FOR SPACECRAFT_SEQ, 'wing-IV');
INSERT INTO SPACECRAFT (SPACECRAFT_ID, SPACECRAFT_NAME) VALUES (NEXT VALUE FOR SPACECRAFT_SEQ, 'wing-V');
INSERT INTO SPACECRAFT (SPACECRAFT_ID, SPACECRAFT_NAME) VALUES (NEXT VALUE FOR SPACECRAFT_SEQ, 'wing-VI');
INSERT INTO SPACECRAFT (SPACECRAFT_ID, SPACECRAFT_NAME) VALUES (NEXT VALUE FOR SPACECRAFT_SEQ, 'space craft I');
INSERT INTO SPACECRAFT (SPACECRAFT_ID, SPACECRAFT_NAME) VALUES (NEXT VALUE FOR SPACECRAFT_SEQ, 'space craft II');
INSERT INTO SPACECRAFT (SPACECRAFT_ID, SPACECRAFT_NAME) VALUES (NEXT VALUE FOR SPACECRAFT_SEQ, 'space craft III');
INSERT INTO SPACECRAFT (SPACECRAFT_ID, SPACECRAFT_NAME) VALUES (NEXT VALUE FOR SPACECRAFT_SEQ, 'space craft IV');
INSERT INTO SPACECRAFT (SPACECRAFT_ID, SPACECRAFT_NAME) VALUES (NEXT VALUE FOR SPACECRAFT_SEQ, 'space craft V');
INSERT INTO SPACECRAFT (SPACECRAFT_ID, SPACECRAFT_NAME) VALUES (NEXT VALUE FOR SPACECRAFT_SEQ, 'space craft VI');



