INSERT INTO SPACECRAFT (SPACECRAFT_ID, SPACECRAFT_NAME) VALUES (NEXT VALUE FOR SPACECRAFT_SEQ, 'wing 1');
INSERT INTO SPACECRAFT (SPACECRAFT_ID, SPACECRAFT_NAME) VALUES (NEXT VALUE FOR SPACECRAFT_SEQ, 'wing-x');
INSERT INTO SPACECRAFT (SPACECRAFT_ID, SPACECRAFT_NAME) VALUES (NEXT VALUE FOR SPACECRAFT_SEQ, 'space craft 1');
INSERT INTO SPACECRAFT (SPACECRAFT_ID, SPACECRAFT_NAME) VALUES (NEXT VALUE FOR SPACECRAFT_SEQ, 'space craft 2');

